# hosts could have been "remote" or "all" as well
- hosts: all
  become: true
  roles:
   - basic

- hosts: webserver
  become: true
  roles:
  - webserver

- hosts: wordpress
  become: true
  roles:
  - wordpress