---
# Setup PHP Repository

- name: Adding PHP Repository Key, Hold on...
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
  register: apt_key
  when: ansible_distribution == 'Debian'

- name: Adding PHP Repository, Hold on...
  apt_repository: repo='deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main' state=present filename=php
  register: repository
  when: ansible_distribution == 'Debian'

- include: roles/libs/tasks/apt/update.yml
  when: repository.changed == True or apt_key.changed == True
