---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Ensure passwordless sudo for user ansible
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%ansible"
    line: "%ansible ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create default user
  user:
    name: "{{ username }}"
    groups: sudo
    password: "{{ password }}"
    shell: /bin/bash
    update_password: always
    state: present

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', public_key) }}"

- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh