---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the mysql packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items:
    - "{{ mysql_pkgs }}"
  when: ansible_os_family == 'RedHat'

- name: Install the mysql packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  become: yes
  become_method: sudo
  with_items:
    - "{{ mysql_pkgs }}"
  environment: "{{ env }}"
  when: ansible_os_family == 'Debian'

- name: Installing MySQL-python
  easy_install: name={{ item }} state=present
  with_items:
    - MySQL-python

- name: Copy the my.cnf file
  template: src=my.cnf.{{ ansible_os_family }}.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify:
   - restart mysql

- name: Create the directory /etc/mysql/conf.d
  file: path=/etc/mysql/conf.d state=directory
  notify:
   - restart mysql

- name: Deploy mysql config to conf.d
  template: src=mysql.cnf.j2 dest=/etc/mysql/conf.d/mysql.cnf
  notify:
    - restart mysql

- name: Start the mysql services
  service: name={{ mysql_service }} state=started enabled=yes

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost
   - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create the database's
  mysql_db:
    name: "{{ website_name }}"
    state: present

- name: Create the database users
  mysql_user: user={{ website_name }} password={{ mysqldbpassword }} state=present priv='{{ website_name }}.*:ALL/*.*:SUPER,RELOAD,SHOW DATABASES'

- name: Tunning MySQL Variables, Hold on...
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: "{{ item.regexp }}"
    backrefs: yes
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^skip-external-locking', line: 'skip-external-locking\nskip-name-resolve' }
    - { regexp: '^connect_timeout', line: 'connect_timeout         = 10' }
    - { regexp: '^wait_timeout', line: "wait_timeout            = 60\ninteractive_timeout     = 30" }
  when: package_install.changed == True

- name: Installing MySQLTunner Script, Hold on...
  get_url:
    url:  http://mysqltuner.pl/
    dest: /usr/local/bin/mysqltuner
    mode: 755
  when: package_install.changed == True
