---
- hosts: appserver
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Gathering Facts
    setup:

  vars:
    username: ansible
    hostname: justanothergeek.nl
    password: $6$rlLdG6wd1CT8v7i$7psP8l26lmaPhT3cigoYYXhjG28CtD1ifILq9KzvA0W0TH2Hj4.iO43RkPWgJGIi60Mz0CsxWbRVBSQkAY95W0
    public_key: roles/security/files/ansible.pub
    wp_mysql_db: localhost
    wp_mysql_user: wordpress
    wp_mysql_password: 8l26lmaPhT3cigoYYXhjG28CtD1ifILq9KzvA0W0TH2Hj4

  roles:
    - bootstrap
    - security
    - appserver
    - php
    - wordpress


#    - reboot
#    - stack
#    - user
#    - website
#    - print
