---
- hosts: appserver
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Gathering Facts
    setup:

  vars:
    username: ansible
    hostname: anothergeek.nl
    website_name: anothergeek.nl
    public_key: roles/security/files/ansible.pub
    wp_mysql_db: localhost
    wp_mysql_user: wordpress

  roles:
    - bootstrap
    - security
    - appserver
    - wordpress
    - print
    - reboot
#    - stack
#    - user
#    - website