---
# tasks file for mysql
- name: Install MySQL packages
  apt: pkg={{item}} state=installed
  become: yes
  become_method: sudo
  with_items:
    - bundler
    - mysql-server-core-5.7
    - mysql-client-core-5.7
    - libmysqlclient-dev
    - python-mysqldb
    - mysql-server
    - mysql-client
    - python3-dev
    - python3-pip
    - build-essential

- name: Install Python2.7 packages
  become: yes
  become_method: sudo
  apt: pkg=python2.7 state=installed
  state: present
  update_cache: yes

- name: create python symlink
  become: yes
  become_method: sudo
    file:
      src: /usr/bin/python2.7
      dest: /usr/bin/python
      owner: root
      group: root
      state: link

- name: Installing PIP software, Hold on...
  become: yes
  become_method: sudo
  pip: name=pip state=latest

- name: Installing passlib software, Hold on...
  become: yes
  become_method: sudo
  pip: name=passlib state=present

- name: Installing MySQL-python software, Hold on...
  become: yes
  become_method: sudo
  pip: name=MySQL-python state=present

- name: Remove the MySQL test database
  action: mysql_db db=test state=absent

- name: Create global my.cnf
  template: src=etc.my.cnf dest=/etc/mysql/my.cnf

- name: Create databases
  mysql_db: name={{item}} state=present collation=utf8_general_ci encoding=utf8
  with_items:
    - "{{wp_mysql_db}}"

- name: Add deploy DB user and allow access to news_* databases
  mysql_user: name={{ wp_mysql_user }} password={{password}} host="%" priv={{wp_mysql_db}}.*:ALL,GRANT state=present

- name: Set root password
  mysql_user: name=root password={{password}} host="{{item}}" priv=*.*:ALL,GRANT state=present
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create local my.cnf for root user
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Restart the MySQL service
  action: service name=mysql state=restarted enabled=true

- name: Set root Password
  become: yes
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Reload privilege tables
  become: yes
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

#- name: Add .my.cnf
# become: yes
#  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Remove anonymous users
  become: yes
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  become: yes
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  become: yes
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  become: yes
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Create mysql database
  become: yes
  mysql_db: name={{ wp_mysql_db }} state=present

- name: Create mysql user
  become: yes
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL