---
- include: roles/website/tasks/php.yml

# Setup MySQL Database
# Generate MySQL DB Name
- name: "Generate MySQl DB Name, Hold on..."
  shell: echo "{{ website_name | lower }}" | tr '.' '_'
  register: db_name

# Fix MySQL username ERROR 1470 (HY000)
- name: "Generate MySQl Username, Hold on..."
  shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n1
  register: db_user

# Generate Random Password For Database
- include: roles/libs/tasks/random_password.yml

- name: Setup Database, Hold on...
  mysql_db:
    name: "{{db_name.stdout }}"
    state: present

- name: Setup Database Permissions, Hold on...
  mysql_user:
    name: "{{ db_user.stdout }}"
    password: "{{ random_password.stdout }}"
    priv: "{{ db_name.stdout }}.*:ALL"
    state: present

- name: Generate Databae Config File for MySQL Website, Hold on...
  template: src=mysql/config.php dest=/home/{{ username | lower }}/vhosts/{{ website_name | lower }}/config.php
  when: website_type == "mysql"
