---
- hosts: appserver1
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Gathering Facts
    setup:

  vars:
    username: ansible
    userpass: Ansible123
    hostname: anothergeek.nl
    website_name: anothergeek
    public_key: roles/security/files/ansible.pub
    mysqldbpassword: "{{ lookup('password', 'credentials/' + '/mysqluserpassword length=25')}}"


  roles:
    - bootstrap
    - security
    - appserver
    - mysql
    - wordpress
    - reboot
    - print