---
- name: service nginx reload
  service: name=nginx state=reloaded

# In order to Fail2ban read new website error.log file
# We need to reload fail2ban
- name: service fail2ban restart
  service: name=fail2ban state=restarted

- name: service php7.1-{{ username | lower }} restart
  service: name=php7.1-{{ username | lower }} state=restarted enabled=yes
