---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Install pwgen
  apt: name=pwgen state=present
  become: yes
  become_method: sudo

- name: Ensure sudo group has sudo privileges
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Ensure passwordless sudo for user {{ username }}
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%ansible"
    line: "%{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: generate linux user password
  local_action: shell /usr/bin/pwgen 16 1
  register: generated_linux_user_password

- name: Create default user
  user:
    name: "{{ username }}"
    password: "{{ lookup('generated_linux_user_password', 'credentials/' + '/password.txt encrypt=md5_crypt') }}"
    shell: /bin/bash
    state: present
    groups: sudo

- name: generate linux root password
  local_action: shell /usr/bin/pwgen 16 1
  register: generated_linux_root_password

- name: Create auto generated password for root
  user:
    name: root
    password: "{{ lookup('generated_linux_root_password', 'credentials/' + '/password.txt encrypt=md5_crypt') }}"

- name: Add authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', public_key) }}"

#- name: Ensure authorized_keys permissions are 0644
#  file:
#    path: \home\ansible\.ssh\authorized_keys
#    mode: 0644

- name: Disable root login
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh service

- name: Disable password authentication
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh service

- name: Ensure sshd_config permissions are 0600
  become: yes
  become_method: sudo
  file:
    path: /etc/ssh/sshd_config
    mode: 0600