---
- name: Enable firewall
  ufw: state=enabled policy=deny

- name: Allow HTTP (port 80)
  ufw: rule=allow port=80 proto=tcp

- name: Allow HTTPS (port 443)
  ufw: rule=allow port=443 proto=tcp

- name: Allow SSH (port 22)
  ufw: rule=allow port=22 proto=tcp