---
- hosts: appserver1
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Gathering Facts
    setup:

  vars:
    username: ansible
    hostname: anothergeek.nl
    website_name: anothergeek
    public_key: roles/security/files/ansible.pub
    rootpass: "{{ lookup('password', 'credentials/' + '/rootpass length=25')}}"
    userpass: "{{ lookup('password', 'credentials/' + '/userpass length=25')}}"
    mysqlrootpassword: "{{ lookup('password', 'credentials/' + '/mysqlrootpassword length=25')}}"
    mysqldbpassword: "{{ lookup('password', 'credentials/' + '/mysqldbpassword length=25')}}"


  roles:
    - bootstrap
    - security
    - appserver
    - mysql
    - wordpress
    - reboot
    - print