---
- name: "Installing VIM"
  apt: pkg=vim state=installed

- name: "Installing Mutli packages"
  apt: pkg={{ item }} state=installed
  with_items:
  - dnsutils
  - git
  - apache2
  - ntp
  - ssh

- name: "Renaming old authorized_keys"
  shell: creates=/home/ansible/.ssh/authorized_keys_old mv /home/ansible/.ssh/authorized_keys /home/ansible/.ssh/authorized_keys_old

- name: "Adding pubkey to authorized keys"
  copy: src=../files/ansible.pub dest=/home/ansible/.ssh/authorized_keys owner=ansible mode=700

