---
- name: "Installing VIM"
  apt: pkg=vim state=installed

- name: "Installing Mutli packages"
  apt: pkg={{ item }} state=installed
  with_items:
  - dnsutils
  - git
  - vim
  - ntp
  - ssh

- name: "Adding bashrc"
  copy: src=../files/ansible.pub dest=/home/ansible/.ssh/authorized_keys1 owner=root mode=8644