---
# Setup User Account
- name: Setup User Account, Hold on...
  user: name={{ username | lower }} shell=/bin/bash
  register: setup_user

- name: Setup User Home Direcroty Permissions, Hold on...
  file:
    path: "/home/{{ username | lower }}"
    mode: "0750"
  when: setup_user.changed == True

# Allow NGINX to Read files
- name: Grant NGINX Read Permissions, Hold on...
  user:
    name: www-data
    groups: "{{ username | lower }}"
    append: yes
  when: setup_user.changed == True

# Setup PS1
- name: Setup Custom Bash Prompt PS1, Hold on...
  shell: echo 'PS1="\`if [ \$? = 0 ]; then echo \[\e[37m\]^_^[\u@\H:\w]\\$ \[\e[0m\]; else echo \[\e[31m\]O_O[\u@\H:\w]\\$ \[\e[0m\]; fi\`"' >> /home/{{ username | lower }}/.bashrc
  when: setup_user.changed == True

# https://github.com/ansible/ansible/issues/9196#issuecomment-57168074
- name: Setup Directory, Hold on...
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username | lower }}"
    group: "{{ username | lower }}"
    mode: "0750"
  with_items:
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/htdocs
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/ssl
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/conf
    - /home/{{ username | lower }}/vhosts/{{ website_name | lower }}/logs
