---
# Print Userful Information

- name: Getting Database Information, Hold on...
  debug:
    msg: "{{ item }}"
  with_items:
    - User = {{ username | lower}}
    - User password = {{ encrypted_user_password.stdout }}
    - Root password = { encrypted_root_password.stdout }}
    - Hostname = {{ hostname }}
    - Website name = {{ website_name }}
    - Publickey = {{ public_key}}
    - SQLDB user pass = {{ mysqluserpassword.stdout }}
    - SQLDB password = {{ mysqlrootpassword.stdout }}