---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  become_method: sudo

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    - apache2
    - mysql-server
    - php-mysql
    - php
    - libapache2-mod-php
    - php-mcrypt
    - python-mysqldb

- name: Set authorized key for root, removing all the authorized key already set
  authorized_key:
    user: root
    key: '{{ item }}'
    state: present
    exclusive: True
  with_file:
    - files/ansible.pub

- name: Set authorized key for ansible, removing all the authorized key already set
  authorized_key:
    user: ansible
    key: '{{ item }}'
    state: present
    exclusive: True
  with_file:
    - files/ansible.pub

- name: Set authorized key for pi, removing all the authorized key already set
  authorized_key:
    user: pi
    key: '{{ item }}'
    state: present
    exclusive: True
  with_file:
    - files/ansible.pub
