---
# tasks file for php
- name: Install php extensions
  apt: name={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    - php-mysql 
    - php-cli 
    - php-curl 
    - php-gd 
    - php-xml 
    - php-mbstring
    - php-fpm
