- hosts: all
  remote_user: root
  vars:
    authorized_key_list:
      - name: root
        authorized_keys:
         - key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
           state: present
  roles:
    - { role: GROG.authorized-key }