---
# Print Userful Information

- name: Getting WordPress Setup Information, Hold on...
  debug:
    msg: "{{ item }}"
  with_items:
    - WordPress Username = {{ username | lower }}
    - WordPress Password = {{ random_password.stdout }}
